version: '3.3'

services: 
  angular:
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    volumes: 
      - './:/projects'
      - '/projects/node_modules'
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
    ports: 
      - '4200:4200'